/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Temp model module.
 * @module model/Temp
 * @version 1.0.0
 */
class Temp {
    /**
     * Constructs a new <code>Temp</code>.
     * @alias module:model/Temp
     * @param tempName {String} 
     */
    constructor(tempName) { 
        
        Temp.initialize(this, tempName);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, tempName) { 
        obj['tempName'] = tempName;
    }

    /**
     * Constructs a <code>Temp</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Temp} obj Optional instance to populate.
     * @return {module:model/Temp} The populated <code>Temp</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Temp();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('tempName')) {
                obj['tempName'] = ApiClient.convertToType(data['tempName'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Temp.prototype['_id'] = undefined;

/**
 * @member {String} tempName
 */
Temp.prototype['tempName'] = undefined;






export default Temp;

